### ISSUE TITLE
undefined reference to `bool QTest::qCompare

### ISSUE THREAD

**Issue by munish-usit** [bricke/Qt-AES#10]
Hi,

While compiling it is giving undefined reference error at 

/lan/ops/cdnshelp/cops/users/smunish/crypto/Qt-AES-master/Qt-AES-master/unit_test/aestest.cpp:197: undefined reference to `bool QTest::qCompare<QString, QByteArray>(QString const&, QByteArray const&, char const*, char const*, char const*, int)'

**Comment by bricke** [comment]
Do you have the QTest installed?

**Comment by AbaoFromCUG** [comment]
Yeach , I have  solved this question!

this is [help](https://stackoverflow.com/questions/29102299/why-does-qcompareqstring1-1-cause-a-linker-error)

> From Qt [documentation](http://doc.qt.io/archives/qt-4.8/qtest.html#QCOMPARE)
> > QCOMPARE is very strict on the data types. Both actual and expected have to be of the same type, otherwise the test won't compile. This prohibits unspecified behavior from being introduced; that is behavior that usually occurs when the compiler implicitly casts the argument.

**Comment by bricke** [comment]
Hi, this is fixed in the latest master, SHA 3d4c882683e146c0b7665b6aad6f682b5c48f205
