### ISSUE TITLE
ASSERT

### ISSUE THREAD

**Issue by nightlight89** [bricke/Qt-AES#11]
ASSERT: "uint(i) < uint(size())" in file c:\work\build\qt5_workdir\w\s\qtbase\src\corelib\tools\qbytearray.h, line 464

**Comment by nightlight89** [comment]
![360 18200501283020](https://user-images.githubusercontent.com/16662984/42610214-052ae59e-85c3-11e8-943e-60f9008d5f2b.png)
this is my code!

**Comment by bricke** [comment]
Not sure where that error is generated but if you don't use a key of the correct length it cannot work.

"HelloWorld" is not 128 bit.
