### ISSUE TITLE
ISO padding: leading zeroes after padding removal

### ISSUE THREAD

**Issue by flaviotordini** [bricke/Qt-AES#14]
I'm not an encryption expert so I may miss something. While evaluating the library I noticed that ISO padding leaves 3 leading zeroed bytes in the plaintext. PKCS7 works fine.

**Comment by bricke** [comment]
ISO padding appends a byte with value 0x80 followed by as many zero bytes as needed to fill the last block.

**Comment by bricke** [comment]
Hi, have you had the chance to retest it recently?

Thank you
