### ISSUE TITLE
Broken RemovePadding(..) truncates whole bytearray

### ISSUE THREAD

**Issue by martinrotter** [bricke/Qt-AES#16]
https://github.com/bricke/Qt-AES/blob/master/qaesencryption.cpp#L37

If `0x80` is not found in `ret`, then `-1` is passed to `truncate(..)` which results in `ret` being [emptied](https://github.com/radekp/qt/blob/master/src/corelib/tools/qbytearray.cpp#L1342).

**Comment by bricke** [comment]
Thank you!
If you have a PR that fixes it I would gladly review it

**Comment by bricke** [comment]
What is the usecase of not finding a 0x80? If you specify it's ISO then there must be a 0x80, if not the whole bytearray is bad or simply not ISO compliant.
Is there an usecase where the 0x80 won't be found?

**Comment by bricke** [comment]
This was fixed in one of the latest PR
