### ISSUE TITLE
it craches

### ISSUE THREAD

**Issue by davidjimmy** [bricke/Qt-AES#21]
i tried using one of your examples and it crashes

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ASSERT: "uint(i) < uint(size())" in file C:/Qt/Qt5.11.0/5.11.0/mingw53_32/include/QtCore/qbytearray.h, line 474

I'm using windows 7
qt 5.11.0

**Comment by SchroterQuentin** [comment]
I'm facing the same issue, could you tell me how you did solve that problem ?
