### ISSUE TITLE
Some of decrypted data is corrupted

### ISSUE THREAD

**Issue by breakersvd** [bricke/Qt-AES#28]
Hi

I am trying to decrypt data that encrypted with (php openssl) with `AES_256 - CBC`

the IV is = `QByteArray iv = "0000000000000000";`

the first section of the data is corrupted and the last is good

what is the problem and how to solve it ?

let me know if you need more info

**Comment by bricke** [comment]
Hello, can you send a sample code? In particular how you are decrypting it and how it was encrypted?

**Comment by breakersvd** [comment]
@bricke 
Thanks for your answer but the problem was solved, it was a wrong calculation of IV

Thanks
