### ISSUE TITLE
May be a problem with QAESEncryption encryption (QAESEncryption::AES_256, QAESEncryption::CBC);

### ISSUE THREAD

**Issue by ptstream** [bricke/Qt-AES#4]
Hi,
Thank you for your job.

 I would like to use QAESEncryption object to encrypt and decrypt some tokens generated by the Google API (https://github.com/ptstream/QtUPnP).

To test your code I try a simple program. 

```
#include <QCoreApplication>
#include "qaesencryption.h"
#include <QCryptographicHash>
#include <QDebug>`

int main(int argc, char *argv[])
{
  QCoreApplication a(argc, argv);
  QAESEncryption encryption (QAESEncryption::AES_256, QAESEncryption::CBC);
  QByteArray input("uuid:e18d497c-e09b-4154-af73-ed7e69d142e8:uuid:2a684c04-66f5-448b-b905-f162334ea75d");
  QByteArray key("your-string-key");
  QByteArray iv ("your-IV-vector");

  QByteArray hashKey = QCryptographicHash::hash(key, QCryptographicHash::Sha256);
  QByteArray hashIV = QCryptographicHash::hash(iv, QCryptographicHash::Sha256);

  QByteArray encodeText = encryption.encode(input, hashKey, hashIV);
  qDebug () << encodeText;

  QByteArray decodeText = encryption.decode(encodeText, hashKey, hashIV);
  qDebug () << decodeText;
  qDebug () << input;

  return 0;
}
```
The function **encode** return always an empty QByteArray. 
This is due to the first test where **m_blocklen=16**, Out the  QCryptographicHash::hash returns a QByteArray with a length of 32.
If I rewrite the constructor like this:
```
// Change m_blocklen(16) by m_blocklen(32)
QAESEncryption::QAESEncryption(QAESEncryption::AES level, QAESEncryption::MODE mode)
    : m_nb(4), m_blocklen(32), m_level(level), m_mode(mode)
```
it seems to work

I do not know anything about cryptography.
Best regards
Patrice

**Comment by frederikvanhoyweghen** [comment]
Bump, same issue.

**Comment by bricke** [comment]
in AES the blocklen is always 128 bits, modifying it to 32 does not respect the AES specs.

**Comment by frederikvanhoyweghen** [comment]
Well the problem is that the current constructor defines m_blocklen as 16, not 32 or even 128, resulting in empty encode results

**Comment by bricke** [comment]
I am working on it

**Comment by bricke** [comment]
The issue seems to be related to CFB and CBC

**Comment by bricke** [comment]
Oh, ok my bad, the samples are not 100% correct. Your code works, the IV vector has to be the same size of the block that is AES is always 128bit, so: 
`QAESEncryption encryption (QAESEncryption::AES_256, QAESEncryption::CBC);
    QByteArray input("uuid:e18d497c-e09b-4154-af73-ed7e69d142e8:uuid:2a684c04-66f5-448b-b905-f162334ea75d");
    QByteArray key("your-string-key");
    QByteArray iv ("your-IV-vector");
    
    QByteArray hashKey = QCryptographicHash::hash(key, QCryptographicHash::Sha256);
    QByteArray hashIV = QCryptographicHash::hash(iv, QCryptographicHash::Md5);
    
    QByteArray encodeText = encryption.encode(input, hashKey, hashIV);
    qDebug () << encodeText;
    
    QByteArray decodeText = encryption.decode(encodeText, hashKey, hashIV);
    qDebug () << QString(decodeText);
    qDebug () << input;`

Please note that I printed your QByteArray as a QString, if you work on pure byte arrays you'll have to deal with the \0 chars that were added as padding.
