### ISSUE TITLE
Convert QByteArray to QString

### ISSUE THREAD

**Issue by seyyedjavadrazavi** [bricke/Qt-AES#55]
I use AES_128 for encoding. After encoding, I want to store the ciphertext to the Sqlite DB. To tackle this, I need to  convert the qbytearray to qstring. I tried all possible way on the web but  the output of the convertors are not the same as the qbytearray.
Is there any other option for me? Foe example is other encoding better than  AES_128 for my purpose? Or other option for converting to QString?

**Comment by bricke** [comment]
I would keep the QByteArray and insert it into the Sqlite as a BLOB
