### ISSUE TITLE
Cannot build with Qt 5.6

### ISSUE THREAD

**Issue by piggz** [bricke/Qt-AES#8]
Your use of QByteArray::insert(int, int, char) was added in 5.7, meaning builds with 5.6 break.

Perhaps you could add some ifdefs around the code and another method for performing the same operation?

**Comment by bricke** [comment]
I added a fix, please check if it works for you: 95104a6ef964718b9721d096b39d111fc85c2bc9

**Comment by piggz** [comment]
builds with the sailfishos sdk now!
